//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Process()
        {
            this.UserProcess = new HashSet<UserProcess>();
            this.WorkFollow = new HashSet<WorkFollow>();
        }
    
        public int ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> CompleteRate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Notes { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> CreateUserID { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProcess> UserProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFollow> WorkFollow { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
