//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YazilimYonetimAraciEntities1 : DbContext
    {
        public YazilimYonetimAraciEntities1()
            : base("name=YazilimYonetimAraciEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<RoleNames> RoleNames { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserLogDetails> UserLogDetails { get; set; }
        public virtual DbSet<UserLogs> UserLogs { get; set; }
        public virtual DbSet<UserProcess> UserProcess { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkFollow> WorkFollow { get; set; }
        public virtual DbSet<WorkFollowDetails> WorkFollowDetails { get; set; }
    }
}
